framework:
    messenger:

        default_bus: command.bus

        buses:
            command.bus:
                middleware:
#                    - doctrine_transaction
            query.bus:
                middleware:
                    - validation
            event.bus:
                default_middleware:
                    enabled: true
                    allow_no_handlers: true
                middleware:
                    - validation

        transports:
            sync: 'sync://'
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
            scheduling-main: '%env(MESSENGER_TRANSPORT_DSN_SCHEDULING_MAIN)%'
            booking-main: '%env(MESSENGER_TRANSPORT_DSN_BOOKING_MAIN)%'

        routing:
             'Bookee\Domain\Navigation\RouteCreatedDomainEvent': [scheduling-main]
             'Bookee\Domain\Scheduling\TripScheduledDomainEvent': [booking-main]

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport title here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
